site_name: Cheat Sheet
site_url: http://thekingofbandit.github.io
site_author: thekingofbandit
site_description: personal notes for tkob.esy.es
extra_javascript: [js/extra.js]
extra_css: [css/extra.css]
repo_url: 'https://github.com/thekingofbandit/thekingofbandit.github.io'
repo_name: 'thekingofbandit/thekingofbandit.github.io'
copyright: ''
google_analytics: ['UA-36723568-3', 'thekingofbandit.github.io']
nav:
    - Home: index.md
    - About: about.md
theme:
    name: material
    custom_dir: custom_theme/
    favicon: 'assets/images/favicon.ico'
    palette:
      primary: 'pink'
      accent: 'pink'
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - type: 'github'
      link: 'https://github.com/thekingofbandit'
    - type: 'twitter'
      link: 'https://twitter.com/thekingofbandit'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/khanafi'