site_name: My Docs
site_url: http://thekingofbandit.github.io
site_author: thekingofbandit
site_description: personal notes for tkob.esy.es
extra_javascript: [js/extra.js]
extra_css: [css/extra.css]
repo_url: 'https://github.com/thekingofbandit/thekingofbandit.github.io/tree/master/Documentation'
repo_name: 'thekingofbandit'
copyright: 'Mohammad Khanafi'
google_analytics: ['UA-36723568-3', 'mkdocs.org']
nav:
    - Home: index.md
    - About: about.md
theme:
    name: slate
    custom_dir: custom_theme/
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
